# Test on output/work_20251209_025156

from cv_filter.filter_gif import filter_gifs_by_relevance

gif_dir = "output/work_20251209_025156/gifs"
grouped_data = [
    {'group_id': 0, 'group_summary': "The video section introduces Machine Learning (ML), an innovative approach in computer science where machines learn to perform tasks without explicit programming instructions—akin to biological organisms acquiring knowledge through experience. The concept, which originated with Arthur Samuel's work at IBM during the late 10th century on a checkers-playing AI system (as mentioned between [0:00:16 - 0:00:21]), has since evolved and is now integral to everyday products. These ML models excel in two primary functions; they classify data, for instance discerning the presence of another car on a roadway as indicated from (0:00:21-0:00:30), thereby enhancing predictive accuracy over time with continuous exposure to vast datasets. The section underscores ML's transformative impact across various industries, facilitating automated decision making and pattern recognition that were once the exclusive domain of human intelligence or complex rule sets.\n\n(Word Count: 125)"},
    {'group_id': 1, 'group_summary': "or which YouTube video do you want to watch next. The first step in the process is to acquire and"},
    {'group_id': 2, 'group_summary': "In a segment from an instructional video focused on Machine Learning (ML), viewers are introduced to how computers can learn tasks without explicit programming through data-driven algorithms. The transcript emphasizes the importance of high-quality, representative datasets for training ML models—underscored by the adage \"Garbage in, garbage out.\" Feature engineering is highlighted as a critical role performed by data scientists to convert raw input into meaningful attributes that capture essential problem characteristics.\n\nThe video further explains how splitting this curated dataset into separate subsets for training and validation purposes allows algorithms like linear or logistic regression—and more complex neural networks, including convolutional ones adept at handling images and language tasks where manual feature engineering is impractical—to iteratively improve their predictive accuracy. The learning process involves the algorithm's predictions being compared against an error function; in classification problems (e.g., identifying animals), this could be measured by model accuracy, while for regression challenges like forecasting bread prices, mean absolute error might serve as a metric of success.\n\nKey takeaways include understanding that data quality is paramount to effective machine learning and the necessity for feature engineering in preparation for training robust models capable of making accurate predictions after iterative refinement based on performance evaluation against predefined metrics tailored to specific types of problems (classification or regression)."},
    {'group_id': 3, 'group_summary': "In this instructional video segment focused on machine learning (ML), viewers are introduced to ML as a method for teaching computers tasks without explicit programming by using algorithms that learn from data over time, thereby enhancing predictive accuracy. The discussion highlights Python's prevalence among data scientists but also acknowledges R and Julia as significant alternatives in the field of machine learning due to their own robust ecosystems tailored for such tasks (0:01:56 - 0:02:01).\n\nThe video further emphasizes that numerous frameworks exist, which aim at making ML accessible by providing tools necessary for data analysis and model development. The core of machine learning is the creation of a predictive 'model'—a file generated from input training datasets (0:02:05 - 0:02:10). These models are designed to take new, unseen inputs in similar formats as they were trained on and produce predictions that minimize prediction errors.\n\nThe ultimate goal of these ML processes is not just theoretical; the predictive model can be implemented onto real devices or deployed into operational environments for practical use (0:02:15 - 0:02:19). The segment underscsores machine learning's transformative potential in various applications, where models act as decision-making aids by interpreting data and making informed predictions.\n\nIn summary, the video educates on ML principles using Python but also recognizes alternatives like R and Julia while stressing frameworks that simplify model creation for predictive analytics with practical deployment capabilities (under 300 words)."},
    {'group_id': 4, 'group_summary': "In a concise introduction to machine learning within an instructional video context (approximately 10 seconds), presenters emphasize that their goal is not only education but also the practical application of concepts, as indicated by mentioning \"real world product.\" This sets up expectations for viewers about translating theoretical knowledge into tangible outcomes.\n\nThe segment further highlights machine learning's core principle: enabling computers to perform tasks without explicit programming instructions through data-driven algorithms that learn and improve over time, as stated in the brief excerpt provided (approximately 6 seconds). The presenters suggest a dynamic process where predictive performance is refined progressively—a central concept of machine learning.\n\nThe closing remarks encourage viewership engagement by inviting them to like more content on their channel and express anticipation for subsequent videos, which implies an educational journey that unfolds over multiple sessions (approximately 6 seconds). The presenters' call-to-action reinforces the interactive nature of learning from this resource.\n\nIn summary, within these brief moments, viewers are introduced to machine learning as a transformative process where data is used for teaching computers tasks without direct programming—a key concept that promises practical applications and continuous improvement in predictive capabilities over time through iterative algorithmic refinement. The segment also encourages active participation by suggesting further content consumption on the channel, indicating an educational series designed to build upon foundational knowledge progressively.\n\n(Word Count: 149)"},
    # Add more grouped data as needed for testing
]

relevant_gifs = filter_gifs_by_relevance(gif_dir, grouped_data, logger=None, use_vision_model=False)

print("Relevant GIFs:")
print(relevant_gifs)
